[project]
name = "github-rag-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.11.0",
    "llama-stack>=0.2.10.1",
    "ollama>=0.5.1",
    "requests>=2.32.3",
    "streamlit>=1.45.1",
]
