replicaCount: 1

image:
  repository: quay.io/ecosystem-appeng/github-rag-ui
  pullPolicy: IfNotPresent
  tag: 0.1.0

service:
  type: ClusterIP
  port: 8501

serviceAccount:
  create: false

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

env:
  - name: LLAMA_STACK_ENDPOINT
    value: 'http://llamastack:8321'

volumes:
  - emptyDir: {}
    name: dot-streamlit
  - emptyDir: {}
    name: dot-cache

volumeMounts:
  - mountPath: /.streamlit
    name: dot-streamlit
  - mountPath: /.cache
    name: dot-cache

global:
  models: {}

pgvector:
  secret:
    user: postgres
    password: rag_password
    dbname: rag_blueprint
    host: pgvector
    port: "5432"